### ISSUE TITLE
Madoko does not compile

### ISSUE THREAD

**Issue by michaeldg** [koka-lang/madoko#37]
Hi,

When using jake to compile madoko I get an error from a semi-hardcoded dependancy:
root@madoko:~/madoko# jake
> ../koka-0.6/out/release/koka-0.6.0-dev -isrc -i../koka-0.6/lib  -c -olib --outname=madoko  -v  main
/bin/sh: 1: ../koka-0.6/out/release/koka-0.6.0-dev: not found
jake aborted.
Error: Process exited with error.
    at api.fail (/usr/lib/node_modules/jake/lib/api.js:336:18)
    at Exec.<anonymous> (/usr/lib/node_modules/jake/lib/utils/index.js:124:9)
(See full trace by running task with --trace)

There is no ../koka-0.6 in my environment.  I guess this is something semi hardcoded from your environment?

Thanks,
Michaël

**Comment by Artoria2e5** [comment]
It's in the Jakefile!

https://github.com/koka-lang/madoko/blob/189505063f76b5c9363c05855a6b405bb85337ce/Jakefile.js#L28-L42
